apiVersion: v1
kind: Service
metadata:
  name: delta-table-check-service
  labels:
    app: pyspark-project
    generell_purpose: service
    specific_purpose: dashboard-service-test
    frontback: frontend
spec:
  selector:
    app: pyspark-project
    generell_purpose: app
    specific_purpose: dashboard-test
    frontback: frontend
  type: NodePort
  ports:
    - name: table-check-service-porz
      protocol: TCP
      port: 90 # The port exposed to the other cluster components; should not be the same as the targetPort/ containerPort
      targetPort: board-port # The port exposed that the component listens to. Can be just the port number or the custom-name of the port if one has been assigned
      nodePort: 31001 # which port is exposed to everything outside of the cluster