apiVersion: v1
kind: Pod
metadata:
  name: selenium-scraper
  labels:
    app: pyspark-project
    generell_purpose: app
    specific_purpose: scraping-script
    frontback: backend
spec:
  securityContext:
      # For security reasons, I run the images as non-root users (implemented in the dockerfiles)
      # However, that prevents me from writing data from my pods to the hostPath PVs.
      # Therefore, I use these options to allow me to do that
      runAsUser: 1000
      runAsGroup: 1000
  containers:
  - name: selenium-scraping-api # Name of the container once started on the pod
    image: an1ls/stream_scrape:ver_2.0 # The image I want to be used
    volumeMounts:
      - mountPath: /app/StreamData
        name: main-mount
        subPath: Target/Entries
      - mountPath: /app/StreamData
        name: main-mount
        subPath: ScrapeCheckpoint
      - mountPath: /app/StreamData
        name: main-mount
        subPath: ScrapingSource
  volumes:
    # Define to which PVC the volume should be connected
    - name: main-mount
      persistentVolumeClaim:
        claimName: main-mount-pvc