apiVersion: v1
kind: Secret
metadata:
    name: sql-secret
type: Opaque
data:
    # These will be sthe user and passwor dused to access the Database
    sql-username: VXNlcg== # The term "User" which was base64 encoded
    sql-password: bGVzc2VydXNlcg== # the term "lesseruser" which was base64 encoded
    # Root password is always required
    sql-root-password: UGFzc3dvcmQxMjMK
    sql-root-username: cm9vdA==
    