apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-mount-pv
  labels:
    app: pyspark-project
    generell_purpose: persistent-volume
    specific_purpose: mount-main-dir
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # the volume will be mounted into the Pod's directory
  accessModes:
    - ReadWriteOnce # All Pods in the Node that this PV is in can acces it to read from and write to it.

  storageClassName: "" 

  hostPath: 
    path: /home/docker/StreamData
    

