version: 2 # again, we need version 2 of the software dbt is using to interact with the .yaml files

sources:
  - name: raw # Name setting. Free to choose
    database: dbt_tutorial # the databse we want to use
    schema: raw # the schema withing the database we want to use
    tables: # the tables within the schema we want to use
      - name: customers
      - name: orders
      - name: payments