# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_pipeline'
config-version: 2
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'analyze_airquality'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_pipeline:
    +materialized: view    # default; override per-model when needed
    staging: # foundation where all individual components (the atoms) are combined to the more complex/ useful models in the project
    intermediate: # where the "atoms" are put together into "molecules". they will exist here
      +unique_key: ["Date", "Hour"]
    marts: # atoms and molecules are combined into fully flegded cells. Aka entity/concept layer
      +unique_key: ["Date", "Hour"]
      +materialized: table
